# Generated by Django 5.2.5 on 2026-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_trial_payment_method_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_external_reference',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_provider_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_provider_label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
