# Generated by Django 5.2.5 on 2026-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscriptioncoupon_promotion_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_model",
            field=models.CharField(
                choices=[
                    ("take_rate_only", "Percentual sobre vendas"),
                    ("minimum_commitment", "Mínimo abatível"),
                    ("custom", "Sob consulta"),
                ],
                default="take_rate_only",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="minimum_monthly_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_paid_order_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="platform_fee_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="product_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="requires_billing_method",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="requires_hubx_checkout",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "billing_model__in",
                        ("take_rate_only", "minimum_commitment", "custom"),
                    )
                ),
                name="subscription_plan_billing_model_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("platform_fee_percent__gte", 0)),
                name="subscription_plan_fee_percent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_monthly_fee__gte", 0)),
                name="subscription_plan_minimum_fee_non_negative",
            ),
        ),
    ]
