# Generated by Django 5.2.13 on 2026-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_subscriptionplan_billing_model_and_more"),
        ("tenants", "0006_tenant_conversion_primary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="billing_method_reference",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="billing_method_status",
            field=models.CharField(
                choices=[
                    ("missing", "Não informado"),
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("failed", "Falhou"),
                ],
                default="missing",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="billing_method_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="tenantsubscription",
            index=models.Index(
                fields=["billing_method_status", "updated_at"],
                name="tenant_sub_bill_method_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "billing_method_status__in",
                        ("missing", "pending", "active", "failed"),
                    )
                ),
                name="tenant_sub_billing_method_status_valid",
            ),
        ),
    ]
