# Generated by Django 5.2.5 on 2026-04-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productimage'),
        ('customers', '0003_customer_execution_flags'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('converted', 'Convertido'), ('abandoned', 'Abandonado'), ('expired', 'Expirado')], default='active', max_length=16)),
                ('currency', models.CharField(default='BRL', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=64)),
                ('converted_checkout_session_key', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(blank=True, max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_sku', models.CharField(blank=True, max_length=120)),
                ('variant_label', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compare_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.product')),
            ],
            options={
                'ordering': ('cart_id', 'sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['tenant', 'status'], name='cart_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['tenant', 'session_key'], name='cart_tenant_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('status', 'active')), fields=('tenant', 'customer'), name='cart_active_unique_customer_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), models.Q(('session_key', ''), _negated=True)), fields=('tenant', 'session_key'), name='cart_active_unique_session_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'variant_sku'], name='cart_item_variant_idx'),
        ),
    ]
