# Generated by Django 5.2.5 on 2026-07-10 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_ownermfarecoverycode"),
        ("tenants", "0006_tenant_conversion_primary_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_email", models.EmailField(blank=True, max_length=254)),
                ("title", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_conversations",
                        to="accounts.owneruser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_conversations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("assistant", "Assistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("llm", "LLM"),
                            ("fallback", "Fallback"),
                            ("system", "Sistema"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.assistantconversation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssistantFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[("useful", "Útil"), ("not_useful", "Não útil")],
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to="assistant.assistantmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["tenant", "updated_at"], name="assistant_conv_tenant_upd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["tenant", "owner_email"], name="assistant_conv_owner_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="assistant_msg_conv_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("user", "assistant", "system"))),
                name="assistant_message_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__in", ("user", "llm", "fallback", "system"))
                ),
                name="assistant_message_source_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantfeedback",
            index=models.Index(
                fields=["message", "created_at"], name="assistant_feedback_msg_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantfeedback",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__in", ("useful", "not_useful"))),
                name="assistant_feedback_value_valid",
            ),
        ),
    ]
