# Generated by Django 5.2.5 on 2026-07-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
