scrape_configs:
  - job_name: hubx-notifications-email-logs
    metrics_path: /notifications/metrics/email-logs/
    scheme: https
    authorization:
      type: Bearer
      credentials: ${NOTIFICATIONS_OBSERVABILITY_TOKEN}
    static_configs:
      - targets:
          - app.hubx.market
