# Generated by Django 5.2.5 on 2026-04-21 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_order_payment_failed_at'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_method_code', models.CharField(blank=True, max_length=64)),
                ('provider_code', models.CharField(blank=True, max_length=64)),
                ('provider_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_code', models.CharField(default='BRL', max_length=8)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', '-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'order', 'status'], name='pay_att_tenant_ord_stat_idx'), models.Index(fields=['tenant', 'external_reference'], name='pay_att_tenant_extref_idx')],
            },
        ),
    ]
