# Generated by Django 5.2.5 on 2026-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='bootstrapped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_request_key',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
