# Generated by Django 5.2.5 on 2026-04-21 18:10

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentattempt_bootstrapped_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                fields=("order",),
                condition=Q(status="pending"),
                name="payments_single_pending_attempt_per_order",
            ),
        ),
    ]
