# Generated by Codex on 2026-04-27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_payment_failed_at"),
        ("payments", "0003_paymentattempt_single_pending_per_order"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("refund_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("idempotency_key", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("blocked", "Bloqueado"),
                            ("processing", "Processando"),
                            ("succeeded", "Concluído"),
                            ("failed", "Falhou"),
                            ("reversed", "Revertido"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency_code", models.CharField(default="BRL", max_length=8)),
                ("provider_code", models.CharField(blank=True, max_length=64)),
                ("external_reference", models.CharField(blank=True, max_length=120)),
                ("provider_refund_reference", models.CharField(blank=True, max_length=120)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_refunds", to="orders.order"),
                ),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentattempt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_refunds", to="tenants.tenant"),
                ),
            ],
            options={
                "ordering": ("tenant_id", "-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["tenant", "order", "status"], name="pay_ref_tenant_ord_stat_idx"),
                    models.Index(fields=["tenant", "status", "created_at"], name="pay_ref_tenant_stat_cr_idx"),
                    models.Index(fields=["tenant", "external_reference"], name="pay_ref_tenant_extref_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "idempotency_key"), name="payments_unique_refund_idempotency_per_tenant"),
                ],
            },
        ),
    ]
