# Generated by Django 5.2.5 on 2026-07-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_orderitem_product_snapshot"),
        ("payments", "0004_paymentrefund"),
        ("tenants", "0006_tenant_conversion_primary_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformFeeLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ledger_key", models.CharField(max_length=180, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("order_take_rate", "Taxa por pedido"),
                            ("pro_minimum_adjustment", "Complemento mínimo Pro"),
                        ],
                        default="order_take_rate",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Esperada"),
                            ("split_requested", "Split solicitado"),
                            ("paid", "Paga"),
                            ("pending_collection", "Cobrança pendente"),
                            ("adjustment_required", "Ajuste necessário"),
                            ("canceled", "Cancelada"),
                        ],
                        default="expected",
                        max_length=32,
                    ),
                ),
                ("plan_code_snapshot", models.CharField(blank=True, max_length=80)),
                ("billing_model_snapshot", models.CharField(blank=True, max_length=32)),
                (
                    "platform_fee_percent_snapshot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "minimum_monthly_fee_snapshot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("billing_period_start", models.DateTimeField(blank=True, null=True)),
                ("billing_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "basis_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency_code", models.CharField(default="BRL", max_length=8)),
                ("provider_code", models.CharField(blank=True, max_length=64)),
                (
                    "provider_split_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "provider_payment_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_fee_ledger_entries",
                        to="orders.order",
                    ),
                ),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_fee_ledger_entries",
                        to="payments.paymentattempt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_fee_ledger_entries",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant_id", "-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "created_at"],
                        name="platform_fee_tenant_stat_idx",
                    ),
                    models.Index(
                        fields=["tenant", "kind", "billing_period_start"],
                        name="platform_fee_period_idx",
                    ),
                    models.Index(
                        fields=["tenant", "order", "kind"],
                        name="platform_fee_order_kind_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ("order_take_rate", "pro_minimum_adjustment"))
                        ),
                        name="platform_fee_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                (
                                    "expected",
                                    "split_requested",
                                    "paid",
                                    "pending_collection",
                                    "adjustment_required",
                                    "canceled",
                                ),
                            )
                        ),
                        name="platform_fee_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("basis_amount__gte", 0)),
                        name="platform_fee_basis_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fee_amount__gte", 0)),
                        name="platform_fee_amount_non_negative",
                    ),
                ],
            },
        ),
    ]
