# Generated by Django 5.2.5 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("badge_label", models.CharField(blank=True, max_length=64)),
                ("badge_variant", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="orders.order")),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
