# Generated by Django 5.2.5 on 2026-04-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=32)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('vip', 'VIP'), ('inactive', 'Inativo')], default='active', max_length=16)),
                ('account_type', models.CharField(blank=True, default='Storefront', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', 'full_name'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='customers_unique_slug_per_tenant'), models.UniqueConstraint(fields=('tenant', 'email'), name='customers_unique_email_per_tenant')],
            },
        ),
    ]
