# Generated by Django 5.2.5 on 2026-04-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Casa', max_length=64)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'ordering': ('customer_id', '-is_default', 'label', 'id'),
            },
        ),
    ]
