# Generated by Django 5.2.5 on 2026-04-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontDiscoveryEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=80)),
                ('session_key_hash', models.CharField(blank=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_discovery_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'event_name', '-occurred_at'], name='cat_disc_tenant_name_idx'), models.Index(fields=['tenant', '-occurred_at'], name='cat_disc_tenant_time_idx')],
            },
        ),
    ]
