# Generated by Django 5.2.5 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0012_order_payment_failed_at"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Criado"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregue"),
                            ("canceled", "Cancelado"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("tracking_code", models.CharField(blank=True, max_length=120)),
                ("tracking_url", models.URLField(blank=True)),
                ("carrier_name", models.CharField(blank=True, max_length=120)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant_id", "-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="ship_tenant_status_idx"),
                    models.Index(fields=["tenant", "tracking_code"], name="ship_tenant_tracking_idx"),
                ],
            },
        ),
    ]
