# Generated by Django 5.2.5 on 2026-04-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shippingprovidersettingshistory'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentstatushistory',
            name='provider_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentstatushistory',
            name='provider_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='shipmentstatushistory',
            index=models.Index(fields=['tenant', 'provider_http_status'], name='ship_hist_provider_http_idx'),
        ),
    ]
