# Generated by Django 5.2.5 on 2026-04-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0002_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_profiles', to='customers.customer'),
        ),
    ]
