# Generated by Django 5.2.5 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile_customer"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("role", models.CharField(default="owner", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("receives_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_users",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant_id", "email"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "email"),
                        name="accounts_owner_unique_email_per_tenant",
                    )
                ],
            },
        ),
    ]
