# Generated by Django 5.2.5 on 2026-05-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_owneruser'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMfaFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('totp', 'TOTP'), ('recovery_code', 'Código de recuperação'), ('external', 'Provider externo')], max_length=32)),
                ('provider_key', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('secret_reference', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_challenged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_factors', to='accounts.owneruser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_mfa_factors', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', 'owner_id', 'factor_type', 'provider_key'),
                'indexes': [models.Index(fields=['tenant', 'owner', 'is_active'], name='accounts_mfa_owner_act_idx'), models.Index(fields=['tenant', 'factor_type'], name='accounts_mfa_tenant_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'owner', 'factor_type', 'provider_key'), name='accounts_mfa_unique_factor_per_owner')],
            },
        ),
    ]
