# Generated by Django 5.2.5 on 2026-05-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ownermfafactor'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMfaRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to='accounts.owneruser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_mfa_recovery_codes', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', 'owner_id', 'created_at'),
                'indexes': [models.Index(fields=['tenant', 'owner', 'used_at'], name='accounts_mfa_rc_owner_idx')],
            },
        ),
    ]
