# Generated by Django 5.2.5 on 2026-04-14 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='open', max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=32)),
                ('shipping_methods', models.JSONField(blank=True, default=list)),
                ('shipping_method_selected', models.CharField(blank=True, max_length=64)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('payment_method_selected', models.CharField(blank=True, max_length=64)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installments_summary', models.CharField(blank=True, max_length=120)),
                ('installments_selected', models.CharField(blank=True, max_length=32)),
                ('installments_options', models.JSONField(blank=True, default=list)),
                ('accept_terms', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='CheckoutSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('meta', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_readonly', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checkoutsession')),
            ],
            options={
                'ordering': ('checkout_session_id', 'sort_order', 'id'),
            },
        ),
    ]
