# Generated by Django 5.2.5 on 2026-04-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkoutsession_completed_order_number'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRecoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_code', models.CharField(max_length=80)),
                ('family', models.CharField(max_length=40)),
                ('severity', models.CharField(blank=True, max_length=24)),
                ('recovery_action', models.CharField(blank=True, max_length=64)),
                ('stage', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(default='checkout_page', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_events', to='checkout.checkoutsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_recovery_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant_id', '-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'result_code', 'created_at'], name='checkout_ch_tenant__212917_idx'), models.Index(fields=['tenant', 'family', 'recovery_action'], name='checkout_ch_tenant__d19d85_idx')],
            },
        ),
    ]
