# Generated by Django 5.2.5 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_event", models.CharField(max_length=64)),
                ("intent_key", models.CharField(max_length=120)),
                ("audience", models.CharField(max_length=32)),
                ("channel", models.CharField(default="email", max_length=32)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=120)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("recipient_delivery_key", models.CharField(max_length=255, unique=True)),
                ("recipient_type", models.CharField(max_length=64)),
                ("recipient_id", models.CharField(max_length=120)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_display_name", models.CharField(blank=True, max_length=150)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_target", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planejado"),
                            ("requested", "Solicitado"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("skipped", "Ignorado"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant_id", "-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="email_logs_tenant_status_idx"),
                    models.Index(fields=["tenant", "source_event"], name="email_logs_tenant_event_idx"),
                ],
            },
        ),
    ]
